version: "3"

networks:
  jots_network:
    driver: bridge

volumes:
  mongodb-data:

services:
  mongo:
    image: mongo-express:0.54.0
    restart: always
    container_name: jots_mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: jots
      ME_CONFIG_MONGODB_ADMINUSERNAME: jots
      ME_CONFIG_MONGODB_ADMINPASSWORD: jots
    volumes:
      - mongodb-data:/data/db/
    ports:
      - "27017:27017"
    networks:
      - jots_network