version: "3"

networks:
  jots_network:
    driver: bridge

volumes:
  mongodb-data:

services:
  mongo:
    image: mongo:4.4.0
    restart: always
    container_name: jots_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: jots
      MONGO_INITDB_ROOT_PASSWORD: jots
      MONGO_INITDB_DATABASE: jots
    volumes:
      - mongodb-data:/data/db/
    ports:
      - "27017:27017"
    networks:
      - jots_network
    command: [--auth]